import type { Product } from "./types";

/**
 * Data contoh untuk development/demo tanpa koneksi Supabase.
 * Isi .env.local dengan kredensial Supabase agar aplikasi memakai database asli.
 */

const now = "2026-08-25T09:00:00.000Z";

function p(product: Partial<Product> & Pick<Product, "name" | "slug">): Product {
  return {
    id: product.slug,
    categoryId: "",
    categorySlug: "makanan-minuman",
    categoryName: "",
    stage: "Sudah Dijual",
    country: "Malaysia",
    shortDescription: "",
    longDescription: "",
    backgroundTypes: [],
    images: [],
    needs: [],
    ownerName: "-",
    ownerEmail: "pemilik@example.com",
    ownerWhatsapp: "-",
    status: "published",
    createdAt: now,
    updatedAt: now,
    ...product,
  } as Product;
}

export const SAMPLE_PRODUCTS: Product[] = [
  p({
    name: "Cemilan Sehat Nusantara",
    slug: "cemilan-sehat-nusantara",
    categorySlug: "makanan-minuman",
    categoryName: "Makanan & Minuman",
    stage: "Sudah Dijual",
    country: "Malaysia",
    city: "Kuala Lumpur",
    shortDescription:
      "Cemilan sehat terbuat dari bahan alami khas Indonesia tanpa pengawet.",
    longDescription:
      "Cemilan Sehat Nusantara adalah camilan yang dibuat dari bahan-bahan alami pilihan khas Indonesia. Diproses secara higienis tanpa bahan pengawet sehingga aman dan sehat untuk dikonsumsi setiap hari.\n\nKami memiliki beberapa varian rasa dan terus berinovasi untuk menghadirkan camilan sehat yang lezat dan bergizi.",
    backgroundTypes: ["UMKM"],
    yearFounded: 2021,
    needs: ["Partner", "Pembeli"],
    ownerName: "Devi Lestari",
    ownerEmail: "owner@cemilansehat.com",
    ownerWhatsapp: "+60 12-345-6789",
    website: "www.cemilansehat.com",
  }),
  p({
    name: "EduPlaner App",
    slug: "eduplaner-app",
    categorySlug: "aplikasi-software",
    categoryName: "Aplikasi & Software",
    stage: "Prototype",
    country: "Jerman",
    city: "Berlin",
    shortDescription: "Aplikasi perencanaan belajar untuk mahasiswa dan pelajar.",
    longDescription:
      "EduPlaner adalah aplikasi perencanaan belajar yang membantu mahasiswa dan pelajar mengatur jadwal, tugas, dan target akademik mereka.\n\nFitur unggulan: pengingat tenggat, statistik kebiasaan belajar, mode fokus, serta komunitas belajar antar diaspora Indonesia.",
    backgroundTypes: ["Startup"],
    yearFounded: 2023,
    needs: ["Investor", "Partner"],
    ownerName: "Rizky Maulana",
    ownerEmail: "hello@eduplaner.app",
    ownerWhatsapp: "+49 151-2345-6789",
    website: "www.eduplaner.app",
  }),
  p({
    name: "Batik Nusa Collection",
    slug: "batik-nusa-collection",
    categorySlug: "fashion-accessories",
    categoryName: "Fashion & Accessories",
    stage: "Sudah Dijual",
    country: "Australia",
    city: "Sydney",
    shortDescription: "Koleksi batik modern dengan sentuhan desain kontemporer.",
    longDescription:
      "Batik Nusa Collection menghadirkan batik asli Indonesia dengan desain modern yang cocok untuk gaya profesional maupun kasual di pasar internasional.\n\nSetiap piece dibuat oleh perajin batik dari Yogyakarta dan Solo dengan pewarna alami.",
    backgroundTypes: ["UMKM", "Komunitas"],
    yearFounded: 2020,
    needs: ["Partner", "Pembeli"],
    ownerName: "Intan Permata",
    ownerEmail: "info@batiknusa.com.au",
    ownerWhatsapp: "+61 412-345-678",
    website: "www.batiknusa.com.au",
  }),
  p({
    name: "EcoStraw Indonesia",
    slug: "ecostraw-indonesia",
    categorySlug: "umkm-kerajinan",
    categoryName: "UMKM & Kerajinan",
    stage: "Prototype",
    country: "Belanda",
    city: "Amsterdam",
    shortDescription: "Sedotan ramah lingkungan berbahan dasar bambu.",
    longDescription:
      "EcoStraw Indonesia memproduksi sedotan minuman dari bambu pilihan yang ramah lingkungan dan dapat digunakan berulang kali.\n\nMisi kami adalah mengurangi sampah plastik sambil memberdayakan petani bambu lokal di Indonesia.",
    backgroundTypes: ["UMKM"],
    yearFounded: 2022,
    needs: ["Partner", "Investor"],
    ownerName: "Bagas Prakoso",
    ownerEmail: "bagas@ecostraw.nl",
    ownerWhatsapp: "+31 6-1234-5678",
  }),
  p({
    name: "Smart Hydroponic System",
    slug: "smart-hydroponic-system",
    categorySlug: "riset-inovasi",
    categoryName: "Riset & Inovasi",
    stage: "Riset",
    country: "Singapura",
    shortDescription: "Sistem hidroponik pintar untuk pertanian urban.",
    longDescription:
      "Smart Hydroponic System adalah riset teknologi pertanian urban yang menggabungkan IoT dan AI untuk mengoptimalkan pertumbuhan tanaman dalam ruangan dengan efisiensi air hingga 90%.\n\nSaat ini kami mencari mentor dan investor untuk melanjutkan pengembangan prototipe komersial.",
    backgroundTypes: ["Komunitas", "Startup"],
    yearFounded: 2024,
    needs: ["Investor", "Mentor"],
    ownerName: "Dr. Amara Wijaya",
    ownerEmail: "amara@hydroponic.sg",
    ownerWhatsapp: "+65 8123-4567",
  }),
  p({
    name: "Buku Anak Dwibahasa",
    slug: "buku-anak-dwibahasa",
    categorySlug: "pendidikan-edukasi",
    categoryName: "Pendidikan & Edukasi",
    stage: "Sudah Dijual",
    country: "Amerika Serikat",
    city: "New York",
    shortDescription: "Buku cerita anak dwibahasa Indonesia–Inggris.",
    longDescription:
      "Buku Anak Dwibahasa membantu anak-anak diaspora Indonesia mengenal bahasa dan budaya Indonesia melalui cerita bergambar yang menghibur.\n\nTersedia dalam format cetak dan digital, dengan seri budaya nusantara, adab, dan kearifan lokal.",
    backgroundTypes: ["Produsen"],
    yearFounded: 2019,
    needs: ["Partner", "Pembeli"],
    ownerName: "Sari Wulandari",
    ownerEmail: "sari@bilingualkids.us",
    ownerWhatsapp: "+1 917-345-6789",
    website: "www.bilingualkids.us",
  }),
  p({
    name: "Kopi Rempah Nusantara",
    slug: "kopi-rempah-nusantara",
    categorySlug: "makanan-minuman",
    categoryName: "Makanan & Minuman",
    stage: "Sudah Dijual",
    country: "Singapura",
    shortDescription: "Kopi arabika single origin dengan sentuhan rempah Indonesia.",
    longDescription:
      "Kopi Rempah Nusantara menghadirkan biji kopi arabika pilihan dari Gayo, Toraja, dan Kintamani yang diproses bersama rempah pilihan seperti kayu manis, kapulaga, dan cengkih.\n\nRoasted fresh setiap minggu di Singapura dan dikirim ke seluruh Asia Tenggara.",
    backgroundTypes: ["UMKM"],
    yearFounded: 2021,
    needs: ["Pembeli", "Distribusi"],
    ownerName: "Hendra Gunawan",
    ownerEmail: "hendra@kopirempah.sg",
    ownerWhatsapp: "+65 8567-1234",
    website: "www.kopirempah.sg",
  }),
  p({
    name: "Teh Herbal Indonesia",
    slug: "teh-herbal-indonesia",
    categorySlug: "makanan-minuman",
    categoryName: "Makanan & Minuman",
    stage: "Sudah Dijual",
    country: "Belanda",
    city: "Rotterdam",
    shortDescription: "Teh herbal premium dari jamu dan tanaman obat Indonesia.",
    longDescription:
      "Teh Herbal Indonesia mengemas kekayaan jamu tradisional dalam bentuk teh modern yang praktis: temulawak, jahe merah, serai, dan rosela.\n\nSemua bahan disuplai langsung dari petani di Jawa Tengah dan diproses tanpa gula tambahan.",
    backgroundTypes: ["UMKM"],
    yearFounded: 2022,
    needs: ["Distribusi", "Pembeli"],
    ownerName: "Ratna Kusuma",
    ownerEmail: "ratna@tehherbal.nl",
    ownerWhatsapp: "+31 6-8765-4321",
  }),
  p({
    name: "Keripik Tempe Nusantara",
    slug: "keripik-tempe-nusantara",
    categorySlug: "makanan-minuman",
    categoryName: "Makanan & Minuman",
    stage: "Sudah Dijual",
    country: "Jerman",
    city: "Munich",
    shortDescription: "Keripik tempe renyah dengan bumbu khas nusantara.",
    longDescription:
      "Keripik Tempe Nusantara adalah camilan berbahan tempe fermentasi pilihan, diiris tipis, digoreng renyah, dan dibalut bumbu khas seperti balado, keju, dan seaweed.\n\nProduksi halal dan terdaftar resmi di Jerman.",
    backgroundTypes: ["Produsen"],
    yearFounded: 2020,
    needs: ["Distribusi"],
    ownerName: "Ahmad Fauzi",
    ownerEmail: "fauzi@tempechips.de",
    ownerWhatsapp: "+49 176-2345-678",
  }),
  p({
    name: "Abon Lele Premium",
    slug: "abon-lele-premium",
    categorySlug: "makanan-minuman",
    categoryName: "Makanan & Minuman",
    stage: "Prototype",
    country: "Arab Saudi",
    city: "Riyadh",
    shortDescription: "Abon lele higienis kaya protein untuk keluarga diaspora.",
    longDescription:
      "Abon Lele Premium memanfaatkan lele hasil budidaya bersertifikat yang diolah menjadi abon rendah garam tanpa MSG.\n\nSedang dalam tahap uji pasar di kalangan komunitas Indonesia di Riyadh sebelum produksi massal.",
    backgroundTypes: ["UMKM"],
    yearFounded: 2023,
    needs: ["Mentor", "Pembeli"],
    ownerName: "Yuni Astuti",
    ownerEmail: "yuni@abonlele.sa",
    ownerWhatsapp: "+966 55-345-6789",
  }),
  p({
    name: "Kue Semprong Tradisional",
    slug: "kue-semprong-tradisional",
    categorySlug: "makanan-minuman",
    categoryName: "Makanan & Minuman",
    stage: "Sudah Dijual",
    country: "Malaysia",
    city: "Johor Bahru",
    shortDescription: "Kue semprong renyah resep turun-temurun dari Riau.",
    longDescription:
      "Kue Semprong Tradisional dibuat dengan resep asli turun-temurun menggunakan santan kelapa asli dan telur ayam kampung, tanpa pengenyal.\n\nCocok untuk hampers, acara hajatan, dan oleh-oleh khas Indonesia.",
    backgroundTypes: ["Produsen"],
    yearFounded: 2018,
    needs: ["Pembeli"],
    ownerName: "Nurhayati",
    ownerEmail: "nurhayati@semprong.my",
    ownerWhatsapp: "+60 19-876-5432",
  }),
  p({
    name: "Tenun Ikat Nusantara",
    slug: "tenun-ikat-nusantara",
    categorySlug: "fashion-accessories",
    categoryName: "Fashion & Accessories",
    stage: "Sudah Dijual",
    country: "Australia",
    city: "Melbourne",
    shortDescription: "Tenun ikat asli Sumba dan Toraja untuk fashion etnik modern.",
    longDescription:
      "Tenun Ikat Nusantara bekerja sama langsung dengan 40+ penenun di Sumba dan Toraja untuk menghadirkan kain tenun berkualitas tinggi ke pasar Australia.\n\nSetiap pembelian memberikan kontribusi langsung kepada perajin.",
    backgroundTypes: ["Komunitas"],
    yearFounded: 2019,
    needs: ["Partner", "Pembeli"],
    ownerName: "Maria Gozali",
    ownerEmail: "maria@tenunnusantara.au",
    ownerWhatsapp: "+61 423-456-789",
  }),
  p({
    name: "Kerajinan Rotan Kalimantan",
    slug: "kerajinan-rotan-kalimantan",
    categorySlug: "umkm-kerajinan",
    categoryName: "UMKM & Kerajinan",
    stage: "Sudah Dijual",
    country: "Belanda",
    city: "Den Haag",
    shortDescription: "Furniture dan dekorasi rotan anyaman artisan Kalimantan.",
    longDescription:
      "Kerajinan Rotan Kalimantan menghadirkan produk anyaman rotan berkualitas ekspor: lampu gantung, keranjang, dan furniture minimalis.\n\nDibuat tangan oleh pengrajin Dayak dengan bahan rotan legal dan berkelanjutan.",
    backgroundTypes: ["UMKM"],
    yearFounded: 2017,
    needs: ["Partner", "Investor"],
    ownerName: "Tomas Anang",
    ownerEmail: "tomas@rotankalimantan.nl",
    ownerWhatsapp: "+31 6-4321-8765",
  }),
  p({
    name: "Kelas Bahasa Indonesia Online",
    slug: "kelas-bahasa-indonesia-online",
    categorySlug: "pendidikan-edukasi",
    categoryName: "Pendidikan & Edukasi",
    stage: "Sudah Dijual",
    country: "Korea Selatan",
    city: "Seoul",
    shortDescription: "Kelas bahasa Indonesia online untuk anak dan dewasa diaspora.",
    longDescription:
      "Kelas Bahasa Indonesia Online menyediakan program pembelajaran interaktif untuk anak diaspora yang ingin tetap fasih berbahasa Indonesia, serta kelas budaya (tari, gamelan, memasak).\n\nPengajar bersertifikat dengan kurikulum adaptif usia 5+.",
    backgroundTypes: ["Komunitas", "Startup"],
    yearFounded: 2021,
    needs: ["Partner", "Mentor"],
    ownerName: "Dian Rahmawati",
    ownerEmail: "dian@belajarindo.kr",
    ownerWhatsapp: "+82 10-3456-7890",
  }),
  // ===== Data contoh untuk demo dashboard admin =====
  p({
    name: "Keripik Ubi Ungu",
    slug: "keripik-ubi-ungu",
    categorySlug: "makanan-minuman",
    categoryName: "Makanan & Minuman",
    stage: "Prototype",
    country: "Singapura",
    shortDescription:
      "Keripik ubi ungu premium tanpa bahan pengawet dengan rasa yang renyah dan manis alami.",
    longDescription:
      "Keripik Ubi Ungu dibuat dari ubi ungu pilihan yang diiris tipis dan dipanggang, bukan digoreng. Kaya antioksidan dan serat.\n\nSaat ini sedang mencari mitra distribusi untuk masuk ke ritel modern di Singapura.",
    backgroundTypes: ["UMKM"],
    yearFounded: 2024,
    needs: ["Pembeli", "Distribusi"],
    ownerName: "Budi Santoso",
    ownerEmail: "budi.santoso@email.com",
    ownerWhatsapp: "+65 9123-4567",
    status: "pending",
    createdAt: "2026-08-24T03:12:00.000Z",
  }),
  p({
    name: "Tasbihku Arga",
    slug: "tasbihku-arga",
    categorySlug: "aplikasi-software",
    categoryName: "Aplikasi & Software",
    stage: "Prototype",
    country: "Arab Saudi",
    city: "Makkah",
    shortDescription:
      "Aplikasi digital tasbih dan pengingat ibadah harian untuk muslim diaspora.",
    longDescription:
      "Tasbihku Arga adalah aplikasi penghitung tasbih digital lengkap dengan jadwal sholat, Al-Qur'an digital, dan komunitas ibadah.\n\nButuh investor untuk pengembangan versi iOS dan fitur premium.",
    backgroundTypes: ["Startup"],
    yearFounded: 2025,
    needs: ["Investor"],
    ownerName: "Andi Wijaya",
    ownerEmail: "andi.wijaya@email.com",
    ownerWhatsapp: "+966 54-123-4567",
    status: "pending",
    createdAt: "2026-08-23T08:40:00.000Z",
  }),
  p({
    name: "HydroFarm System",
    slug: "hydrofarm-system",
    categorySlug: "riset-inovasi",
    categoryName: "Riset & Inovasi",
    stage: "Riset",
    country: "Singapura",
    shortDescription:
      "Modul hidroponik rumahan hemat ruang untuk apartemen di kota besar.",
    longDescription:
      "HydroFarm System adalah modul hidroponik vertikal ukuran compact yang dirancang untuk apartemen kecil. Dilengkapi sensor nutrisi dan aplikasi monitoring.\n\nSaat ini tahap riset bersama universitas lokal.",
    backgroundTypes: ["Komunitas"],
    yearFounded: 2025,
    needs: ["Mentor", "Investor"],
    ownerName: "Rizky Pratama",
    ownerEmail: "rizky.pratama@email.com",
    ownerWhatsapp: "+65 8765-1234",
    status: "pending",
    createdAt: "2026-08-22T11:05:00.000Z",
  }),
  p({
    name: "Kopi Luwak Rintik Jawa",
    slug: "kopi-luwak-rintik-jawa",
    categorySlug: "makanan-minuman",
    categoryName: "Makanan & Minuman",
    stage: "Sudah Dijual",
    country: "Jepang",
    city: "Tokyo",
    shortDescription:
      "Kopi luwak asli Jawa Timur dengan proses etis dan bersertifikat.",
    longDescription:
      "Kopi Luwak Rintik Jawa bekerja sama dengan peternak luwak etis di Jawa Timur. Setiap batch disertifikasi asli dan dapat dilacak.\n\nMencari partner distribusi di Jepang.",
    backgroundTypes: ["Produsen"],
    yearFounded: 2020,
    needs: ["Partner", "Distribusi"],
    ownerName: "Agus Setiawan",
    ownerEmail: "agus.setiawan@email.com",
    ownerWhatsapp: "+81 90-1234-5678",
    status: "pending",
    createdAt: "2026-08-20T02:30:00.000Z",
  }),
  p({
    name: "Gadget Organizer Kulit",
    slug: "gadget-organizer-kulit",
    categorySlug: "fashion-accessories",
    categoryName: "Fashion & Accessories",
    stage: "Sudah Dijual",
    country: "Malaysia",
    city: "Penang",
    shortDescription: "Organizer gadget berbahan kulit asli buatan pengrajin Garut.",
    longDescription:
      "Gadget Organizer Kulit memadukan bahan kulit sapi asli Garut dengan desain minimalis untuk menyimpan kabel, charger, dan aksesori.\n\nPerlu revisi foto produk dan penjelasan sertifikasi kulit sebelum tayang.",
    backgroundTypes: ["UMKM"],
    yearFounded: 2022,
    needs: ["Pembeli"],
    ownerName: "Fajar Nugroho",
    ownerEmail: "fajar.nugroho@email.com",
    ownerWhatsapp: "+60 11-2345-6789",
    status: "revision",
    reviewNote:
      "Mohon lengkapi foto produk (min. 3 foto) dan tambahkan keterangan sertifikasi bahan kulit.",
    createdAt: "2026-08-18T07:15:00.000Z",
  }),
  p({
    name: "Jasa Kirim Paket Antarnegara",
    slug: "jasa-kirim-paket-antarnegara",
    categorySlug: "umkm-kerajinan",
    categoryName: "UMKM & Kerajinan",
    stage: "Prototype",
    country: "Hong Kong",
    shortDescription: "Layanan antar paket Indonesia–Hong Kong dengan harga bersahabat.",
    longDescription:
      "Layanan jasa kirim paket rutin Indonesia–Hong Kong untuk kebutuhan diaspora: makanan halal, dokumen, dan barang pribadi.",
    backgroundTypes: ["Startup"],
    yearFounded: 2024,
    needs: ["Investor"],
    ownerName: "-",
    ownerEmail: "kontak@kirimhk.example",
    ownerWhatsapp: "-",
    status: "rejected",
    reviewNote:
      "Ditolak: layanan logistik memerlukan verifikasi legalitas perusahaan. Silakan ajukan kembali dengan dokumen izin usaha.",
    createdAt: "2026-08-15T04:00:00.000Z",
  }),
];
